In [1]:
import numpy as np 



In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]], dtype=float)

# 1. 奇异值分解 SVD
U, s, Vt = np.linalg.svd(A)
print("左奇异矩阵 U:\n", U)
print("奇异值 (Singular values):", s)
print("右奇异矩阵 Vᵀ:\n", Vt)

# 2. 计算 Moore-Penrose 广义伪逆 A⁺
A_pinv = np.linalg.pinv(A)
print("广义伪逆 A⁺:\n", A_pinv)

左奇异矩阵 U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
奇异值 (Singular values): [9.52551809 0.51430058]
右奇异矩阵 Vᵀ:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
广义伪逆 A⁺:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
