In [1]:
import numpy as np 



In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]], dtype=float)

# 1. 奇异值分解 SVD
U, s, Vt = np.linalg.svd(A)
print("左奇异矩阵 U:\n", U)
print("奇异值 (Singular values):", s)
print("右奇异矩阵 Vᵀ:\n", Vt)

# 2. 计算 Moore-Penrose 广义伪逆 A⁺
A_pinv = np.linalg.pinv(A)
print("广义伪逆 A⁺:\n", A_pinv)

左奇异矩阵 U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
奇异值 (Singular values): [9.52551809 0.51430058]
右奇异矩阵 Vᵀ:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
广义伪逆 A⁺:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [2]:
import numpy as np
v = np.array([[1,0]])
vT = v.T

print(f"v =\n{v}")
print(f"vT=\n{vT}")
print(f"v*vt=\n{v*vT}")


v =
[[1 0]]
vT=
[[1]
 [0]]
v*vt=
[[1 0]
 [0 0]]


In [4]:
np.random.seed(42)
mean = [0, 0, 0]
cov_true = np.array([[4.0, 1.8, 0.2],
                     [1.8, 2.0, 0.5],
                     [0.2, 0.5, 1.0]])  # 对称正定协方差矩阵
X = np.random.multivariate_normal(mean, cov_true, size=1000)

# 2. 中心化并计算样本协方差矩阵
X_centered = X - np.mean(X, axis=0)
Sigma = (X_centered.T @ X_centered) / (len(X) - 1)

# 3. 对实对称矩阵调用专属高精度算法 eigh (返回升序特征值和正交特征向量)
eigenvalues, Q = np.linalg.eigh(Sigma)

# 倒序排列：使得最大特征值排在最前
idx = np.argsort(eigenvalues)[::-1]
evals_sorted = eigenvalues[idx]
Q_sorted = Q[:, idx]

print("=== 样本协方差矩阵谱分解结果 ===")
print("各主轴特征值 (方差贡献):", np.round(evals_sorted, 4))
explained_variance_ratio = evals_sorted / np.sum(evals_sorted)
print("方差解释率占比:        ", np.round(explained_variance_ratio * 100, 2), "%")

# 4. 谱分解重构矩阵验证: A = Q @ diag(evals) @ Q^T
Sigma_reconstructed = Q_sorted @ np.diag(evals_sorted) @ Q_sorted.T
reconstruction_err = np.linalg.norm(Sigma - Sigma_reconstructed)
print(f"外积谱分解重构误差 ||A - QΛQ^T||: {reconstruction_err:.2e} (完全精确！")
print(Q)

=== 样本协方差矩阵谱分解结果 ===
各主轴特征值 (方差贡献): [4.8083 1.2953 0.5956]
方差解释率占比:         [71.77 19.34  8.89] %
外积谱分解重构误差 ||A - QΛQ^T||: 2.69e-15 (完全精确！
[[ 0.28066262 -0.40678734 -0.8693403 ]
 [-0.62969342  0.6055323  -0.48663829]
 [ 0.72437193  0.68399904 -0.08620103]]


In [18]:
print(Q[0])
print(np.square(Q[0]))
print(Q.T[0])
print(np.square(Q.T[0]))


[ 0.28066262 -0.40678734 -0.8693403 ]
[0.07877151 0.16547594 0.75575255]
[ 0.28066262 -0.62969342  0.72437193]
[0.07877151 0.3965138  0.52471469]


In [8]:
import numpy as np 
x = np.array([[1,1],[1,-1]])
sigma  = np.array([[3,0],[0,1]])
print(x)
print(sigma)
print (np.dot(sigma,x))
print(sigma@x)

[[ 1  1]
 [ 1 -1]]
[[3 0]
 [0 1]]
[[ 3  3]
 [ 1 -1]]
[[ 3  3]
 [ 1 -1]]
